 version: '3.1'
 services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db

  apache:
    image: php:7.0-apache
    container_name: apache
    ports:
    - 80:80
    volumes:
    - /home/iriartex/iPortfolio:/var/www/html
    environment:
      PMA_HOST: db
  
  db:
    image: mariadb:10.6
    container_name: db
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: db_home
      MYSQL_USER: sysadmin
      MYSQL_PASSWORD: sysadmin
      MYSQL_ROOT_PASSWORD: toor
  
        #  first-app:
        #    image: app:2.1
        #    links: 
        #      - mariadb:mariadb

        #    ports:
        #      - 4000:3000
  
    
