version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_tienda
    expose:
      - 3306
    networks:
      servers:
        ipv4_address: 194.168.200.11

  app:
    image: joseco/backend:2.2
    ports:
      - 5000:3000
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: toor
      DB_NAME: db_tienda
      DB_PORT: 3306

    networks:
      servers:
        ipv4_address: 194.168.200.10
      
  
networks:
  servers:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "194.168.200.0/24"
          gateway: "194.168.200.1"



